### ISSUE TITLE
suggestion: deep freeze

### ISSUE THREAD

**Issue by crazy4groovy** [thenativeweb/datasette#1]
For performance: 

You may consider using a [deep freeze](https://www.npmjs.com/search?q=freeze%20deep) package to encourage data immutability, instead of deep cloning objects so many times.

Cheers

**Comment by goloroden** [comment]
Thanks a lot for bringing up this idea 😊 

Would you mind creating a PR for that?

**Comment by goloroden** [comment]
Closed for now. For the explanation why, please see the referenced PR.
